[package]
name = "lzxd"
version = "0.1.0"
authors = ["Matthew D. Steele <mdsteele@alum.mit.edu>"]
description = "Encode/decode LZXD-compressed data"
repository = "https://github.com/mdsteele/rust-lzxd"
keywords = ["compression", "lzx", "lzxd"]
license = "MIT"
readme = "README.md"

[dependencies]
byteorder = "1"
